name: Sync LeetCode CN to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: LeetCode CN Sync
        uses: Zou8080/leetcode-cn-sync@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leetcode_cookies: ${{ secrets.LEETCODE_CN_COOKIE }}
