name: Sync LeetCode
on:
  workflow_dispatch:      # 允许手动触发（用于全量同步历史）
  schedule:
    - cron: "0 8 * * *"   # 每天北京时间 16:00 自动运行一次

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@master
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-submissions # 代码存放目录
          verbose: true
          commit-header: '[LeetCode Sync]' # 提交信息前缀
          leetcode-site: cn
